print("Available scripts:")
print("  python -m app.scripts.reconcile_stripe [--dry-run]")
print("  python -m app.scripts.audit_credits [--fix]")
print("  python -m app.scripts.probe_auth --url URL")
print("  python -m app.scripts.verify_deploy --url URL")
